{
 "title": "Error Events Dashboard",
 "tags": [
  "log",
  "error",
  "system"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "window", "label": "Window", "query": "1m" }
  ]
 },
 "panels": [
  {
   "title": "Xu hướng Sự kiện Lỗi Hệ thống (Theo Host/Loại Lỗi)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"logs\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"error_events\" and r._field == \"count\")\n  |> map(fn: (r) => ({r with _value: float(v: r._value)}))\n  |> aggregateWindow(every: 5m, fn: sum)\n  |> fill(value: 0.0)\n  |> group(columns: [\"hostname\", \"message_class\"], mode: \"by\")\n  |> map(fn: (r) => ({r with _series_name: r.hostname + \" / \" + r.message_class}))\n  |> drop(columns: [\"_field\", \"_measurement\", \"hostname\", \"message_class\"])\n  |> yield(name: \"error_trend\")\n"
    }
   ]
  },
  {
   "title": "Tổng Số Lỗi ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"logs\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"error_events\" and r._field == \"count\")\n  |> group(columns: [\"message_class\"])\n  |> sum(column: \"_value\")\n  |> rename(columns: {_value: \"total_errors\"})\n  |> keep(columns: [\"message_class\", \"total_errors\"])\n  |> yield(name: \"error_count_by_message_class\")\n"
    }
   ]
  },
  {
   "title": "Tỷ lệ Lỗi theo Hostname (%)",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"logs\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"error_events\" and r._field == \"count\")\n|> group(columns: [\"hostname\"])\n|> sum(column: \"_value\")\n|> rename(columns: {\"_value\": \"Total Errors\"})\n|> keep(columns: [\"hostname\", \"Total Errors\"])\n|> yield(name: \"hostname_errors\")"
    }
   ]
  },
  {
   "title": "Sự kiện Lỗi Gần nhất (Host và Loại lỗi)",
   "type": "table",
   "gridPos": { "h": 11, "w": 9, "x": 6, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"logs\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r._measurement == \"error_events\" and\n      r._field == \"count\"\n  )\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 5)\n  |> map(fn: (r) => ({\n      _time: r._time,\n      detail: r.hostname + \" | \" + r.level + \" | \" + r.message_class\n  }))\n  |> keep(columns: [\"_time\", \"detail\"])\n  |> yield(name: \"last_5_error_details\")\n"
    }
   ]
  },
  {
   "title": "Sự kiện Lỗi Hàng đầu (Theo Host và Loại Lỗi)",
   "type": "table",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"logs\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"error_events\" and\n    r._field == \"count\"\n  )\n  |> group(columns: [\"hostname\", \"message_class\"])\n  |> sum(column: \"_value\")\n  |> map(fn: (r) => ({\n      r with\n      Detail: r.hostname + \" / \" + r.message_class,\n      Total: r._value\n  }))\n  |> keep(columns: [\"Detail\", \"Total\"])\n  |> sort(columns: [\"Total\"], desc: true)\n  |> yield(name: \"error_summary_table\")\n"
    }
   ]
  }
 ]
}