{
 "title": "Top URLs Dashboard",
 "tags": [
  "influxdb",
  "http",
  "urls"
 ],
 "time": { "from": "2025-10-11T08:18:39.842Z", "to": "2025-10-13T08:18:39.842Z" },
 "panels": [
  {
   "title": "Tỷ lệ HTTP Status Codes (2h qua)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"logs\") |> range(start: -2h) |> filter(fn: (r) => r._measurement == \"top_urls\" and r._field == \"count\") |> group(columns: [\"status\"]) |> sum() |> keep(columns: [\"_value\", \"status\", \"_time\"]) |> yield(name: \"result\")"
    }
   ]
  },
  {
   "title": "Tỷ lệ Phân phối Lỗi (4xx/5xx) theo Hostname (2h qua)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"logs\") |> range(start: -2h) |> filter(fn: (r) => r._measurement == \"top_urls\" and r._field == \"count\") |> filter(fn: (r) => r.status =~ /^4.*/ or r.status =~ /^5.*/) |> group(columns: [\"hostname\"]) |> sum() |> sort(columns: [\"_value\"], desc: true) |> limit(n: 5) |> keep(columns: [\"_value\", \"hostname\", \"_time\"]) |> yield(name: \"result\")"
    }
   ]
  },
  {
   "title": "Top 10 lỗi nhiều nhất theo Status Code (2h qua)",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"logs\") |> range(start: -2h) |> filter(fn: (r) => r._measurement == \"top_urls\" and r._field == \"count\") |> filter(fn: (r) => r.status =~ /^4.*/ or r.status =~ /^5.*/ ) |> group(columns: [\"status\", \"path\", \"hostname\"]) |> sum() |> map(fn: (r) => ({ r with label: r.status + \" | \" + r.hostname + \" | \" + r.path })) |> sort(columns: [\"_value\"], desc: true) |> limit(n: 10) |> keep(columns: [\"_value\", \"label\", \"_time\"]) |> yield(name: \"result\")"
    }
   ]
  },
  {
   "title": "Top 10 URL được truy cập nhiều nhất (2h qua)",
   "type": "barchart",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"logs\") |> range(start: -2h) |> filter(fn: (r) => r._measurement == \"top_urls\" and r._field == \"count\") |> group(columns: [\"hostname\", \"path\"]) |> sum() |> map(fn: (r) => ({ r with label: r.hostname + \" | \" + r.path })) |> sort(columns: [\"_value\"], desc: true) |> limit(n: 10) |> keep(columns: [\"_value\", \"label\", \"_time\"]) |> yield(name: \"result\")"
    }
   ]
  }
 ]
}